-- File auto generated by purescript-bridge! --
module GenerateClient.Types where

import Data.Lens (Lens', Prism', lens, prism')
import Data.Maybe (Maybe(..))
import Prim (Boolean, String)

import Prelude
import Data.Generic (class Generic)

newtype EmailProperties =
    EmailProperties {
      subscribed :: Boolean
    }

derive instance genericEmailProperties :: Generic EmailProperties

--------------------------------------------------------------------------------
_EmailProperties :: Prism' EmailProperties { subscribed :: Boolean}
_EmailProperties = prism' EmailProperties f
  where
    f (EmailProperties r) = Just r


--------------------------------------------------------------------------------
newtype Token =
    Token {
      unToken :: String
    }

derive instance genericToken :: Generic Token

--------------------------------------------------------------------------------
_Token :: Prism' Token { unToken :: String}
_Token = prism' Token f
  where
    f (Token r) = Just r


--------------------------------------------------------------------------------
newtype UriEmail =
    UriEmail {
      unUriEmail :: String
    }

derive instance genericUriEmail :: Generic UriEmail

--------------------------------------------------------------------------------
_UriEmail :: Prism' UriEmail { unUriEmail :: String}
_UriEmail = prism' UriEmail f
  where
    f (UriEmail r) = Just r


--------------------------------------------------------------------------------
